### ISSUE TITLE
Another missing image file for unit tests 16gray.tif

### ISSUE THREAD

**Issue by Synchronicity89** [gapml/CV#9]
`
self = <tests.image_test.MyTest testMethod=test_054>

    def test_054(self):
        """ Images - image types """

        # gif - grayscale
        images = Images('foo', ['files/8rgb.gif'], 0, config=['grayscale'])
        self.assertEqual(images.count, 1)

        # gay tiff - color
        images = Images('foo', ['files/16gray.tif'], 0, config=['16bpp'])
>       self.assertEqual(images.count, 1)
E       AssertionError: 0 != 1

image_test.py:4604: AssertionError`

**Comment by virtualdvid** [comment]
Thanks, loaded the missing image.

**Comment by virtualdvid** [comment]
Thanks, loaded the missing image.
